version: "3.8"

services:
  influxdb:
    image: influxdb:1.8.2-alpine
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=asupersecretpassword
      - INFLUXDB_USER=fping
      - INFLUXDB_USER_PASSWORD=anotsosecretpassword
    volumes:
      - ./influxdb:/docker-entrypoint-initdb.d
    ports:
      - "8083:8083" # admin port
      - "8086:8086" # db port

  grafana:
    image: grafana/grafana:7.1.5
    environment:
      - GF_PATHS_PROVISIONING=/mnt/provisioning
    volumes:
      - ./grafana:/mnt/provisioning
    ports:
      - "3031:3000" # admin port

  infpingrb:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INFLUXDB_HOSTNAME=influxdb
      - INFLUXDB_DATABASE=infping_rb_testing
      - INFLUXDB_USERNAME=infping
      - INFLUXDB_PASSWORD=anotsosecretpassword
      - HOSTS=1.1.1.1,8.8.8.8

